name: wechat_camera_picker
description: A camera picker based on WeChat's UI which is a separate runnable extension to wechat_assets_picker.
repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
version: 3.7.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0
  camera_platform_interface: ^2.1.5
  collection: ^1.16.0
  meta: ^1.7.0
  path: ^1.8.1
  photo_manager: ^2.1.4
  uuid: ^3.0.6
  video_player: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1